include:
  - board: xiao_ble
    shield: totem_left
  - board: xiao_ble
    shield: totem_right
  - board: xiao_ble # Replace with the Xiao-compatible board you're using
    shield: tester_xiao
  - board: xiao_ble
    shield: settings_reset
# there is no settingsreset (needed) for the XIAO
